# Custom handling of levels
# https://docs.python.org/zh-cn/3/howto/logging-cookbook.html 
# TimedRotatingFileHandler
# https://docs.python.org/zh-cn/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler
version: 1
# 是否要禁用任何现有的非根日志记录器。如果省略，则此形参默认为 True。
disable_existing_loggers: True

formatters:
  tostdout:
    format: "%(asctime)s %(levelname)s %(process)s-%(filename)s-%(lineno)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  tofile:
    format: "%(asctime)s %(levelname)s %(process)s-%(filename)s-%(lineno)s: %(message)s"
    # datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  sh:
    class: logging.StreamHandler
    level: INFO
    formatter: tostdout
    stream: ext://sys.stdout
  fh:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/etl.log
    encoding: utf-8
    interval: 1
    backupCount: 31
    when: D
    level: INFO
    formatter: tofile

# loggers:
#   log_sh:
#     level: DEBUG
#     handlers: [sh]
#     #是否往上级Logger传递，如果为yes的话，root选择了两个logger，这里的日志也会在两个logger的配置中输出，会重复。所以选No,自己记录自己的日志。
#     propagate: no

#   log_fh:
#     level: DEBUG
#     handlers: [fh]
#     propagate: False

root:
  level: DEBUG
  handlers: [sh,fh]